"""
===============================================================================
File: market_tick.py

Purpose:
    Represents a single market update generated by the Exchange Simulator.

Business Problem:
    Passing dictionaries throughout the application quickly becomes
    difficult to maintain and error-prone.

    A dedicated data model provides:
        - Type safety
        - Better readability
        - IDE auto-completion
        - Easier testing

===============================================================================
"""

from dataclasses import dataclass


@dataclass(slots=True)
class MarketTick:
    """
    Represents the latest state of a market instrument.
    """

    symbol: str

    price: float

    open_price: float

    high: float

    low: float

    volume: int

    timestamp: str
